const pokedex = [
    {name: "Bulbasaur", hp: 45, atk: 49, move: "Tackle", type: "Grass", rarity: "Common"},
    {name: "Ivysaur", hp: 60, atk: 62, move: "Vine Whip", type: "Grass", rarity: "Uncommon"},
    {name: "Venusaur", hp: 80, atk: 82, move: "Solar Beam", type: "Grass", rarity: "Rare"},
    {name: "Charmander", hp: 39, atk: 52, move: "Ember", type: "Fire", rarity: "Common"},
    {name: "Charmeleon", hp: 58, atk: 64, move: "Flamethrower", type: "Fire", rarity: "Uncommon"},
    {name: "Charizard", hp: 78, atk: 84, move: "Fire Blast", type: "Fire", rarity: "Rare"},
    {name: "Squirtle", hp: 44, atk: 48, move: "Water Gun", type: "Water", rarity: "Common"},
    {name: "Wartortle", hp: 59, atk: 63, move: "Bubble Beam", type: "Water", rarity: "Uncommon"},
    {name: "Blastoise", hp: 79, atk: 83, move: "Hydro Pump", type: "Water", rarity: "Rare"},
    {name: "Caterpie", hp: 45, atk: 30, move: "Tackle", type: "Bug", rarity: "Common"},
    {name: "Metapod", hp: 50, atk: 20, move: "Harden", type: "Bug", rarity: "Uncommon"},
    {name: "Butterfree", hp: 60, atk: 45, move: "Confusion", type: "Bug", rarity: "Rare"},
    {name: "Weedle", hp: 40, atk: 35, move: "Poison Sting", type: "Bug", rarity: "Common"},
    {name: "Kakuna", hp: 45, atk: 25, move: "Harden", type: "Bug", rarity: "Uncommon"},
    {name: "Beedrill", hp: 65, atk: 90, move: "Twineedle", type: "Bug", rarity: "Rare"},
    {name: "Pidgey", hp: 40, atk: 45, move: "Gust", type: "Normal", rarity: "Common"},
    {name: "Pidgeotto", hp: 63, atk: 60, move: "Wing Attack", type: "Normal", rarity: "Uncommon"},
    {name: "Pidgeot", hp: 83, atk: 80, move: "Sky Attack", type: "Normal", rarity: "Rare"},
    {name: "Rattata", hp: 30, atk: 56, move: "Quick Attack", type: "Normal", rarity: "Common"},
    {name: "Raticate", hp: 55, atk: 81, move: "Hyper Fang", type: "Normal", rarity: "Uncommon"},
    {name: "Spearow", hp: 40, atk: 60, move: "Peck", type: "Normal", rarity: "Common"},
    {name: "Fearow", hp: 65, atk: 90, move: "Drill Peck", type: "Normal", rarity: "Uncommon"},
    {name: "Ekans", hp: 35, atk: 60, move: "Poison Sting", type: "Poison", rarity: "Common"},
    {name: "Arbok", hp: 60, atk: 85, move: "Wrap", type: "Poison", rarity: "Uncommon"},
    {name: "Pikachu", hp: 35, atk: 55, move: "Thunder Shock", type: "Electric", rarity: "Common"},
    {name: "Raichu", hp: 60, atk: 90, move: "Thunderbolt", type: "Electric", rarity: "Uncommon"},
    {name: "Sandshrew", hp: 50, atk: 75, move: "Scratch", type: "Ground", rarity: "Common"},
    {name: "Sandslash", hp: 75, atk: 100, move: "Slash", type: "Ground", rarity: "Uncommon"},
    {name: "Nidoran♀", hp: 55, atk: 47, move: "Scratch", type: "Ground", rarity: "Common"},
    {name: "Nidorina", hp: 70, atk: 62, move: "Bite", type: "Ground", rarity: "Uncommon"},
    {name: "Nidoqueen", hp: 90, atk: 82, move: "Body Slam", type: "Ground", rarity: "Rare"},
    {name: "Nidoran♂", hp: 46, atk: 57, move: "Peck", type: "Ground", rarity: "Common"},
    {name: "Nidorino", hp: 61, atk: 72, move: "Horn Attack", type: "Ground", rarity: "Uncommon"},
    {name: "Nidoking", hp: 81, atk: 92, move: "Thrash", type: "Ground", rarity: "Rare"},
    {name: "Clefairy", hp: 70, atk: 45, move: "Pound", type: "Normal", rarity: "Common"},
    {name: "Clefable", hp: 95, atk: 70, move: "Double Slap", type: "Normal", rarity: "Uncommon"},
    {name: "Vulpix", hp: 38, atk: 41, move: "Ember", type: "Fire", rarity: "Common"},
    {name: "Ninetales", hp: 73, atk: 76, move: "Flamethrower", type: "Fire", rarity: "Uncommon"},
    {name: "Jigglypuff", hp: 115, atk: 45, move: "Sing", type: "Normal", rarity: "Common"},
    {name: "Wigglytuff", hp: 140, atk: 70, move: "Double Slap", type: "Normal", rarity: "Uncommon"},
    {name: "Zubat", hp: 40, atk: 45, move: "Leech Life", type: "Poison", rarity: "Common"},
    {name: "Golbat", hp: 75, atk: 80, move: "Wing Attack", type: "Poison", rarity: "Uncommon"},
    {name: "Oddish", hp: 45, atk: 50, move: "Absorb", type: "Grass", rarity: "Common"},
    {name: "Gloom", hp: 60, atk: 65, move: "Acid", type: "Grass", rarity: "Uncommon"},
    {name: "Vileplume", hp: 75, atk: 80, move: "Petal Dance", type: "Grass", rarity: "Rare"},
    {name: "Paras", hp: 35, atk: 70, move: "Scratch", type: "Bug", rarity: "Common"},
    {name: "Parasect", hp: 60, atk: 95, move: "Slash", type: "Bug", rarity: "Uncommon"},
    {name: "Venonat", hp: 60, atk: 55, move: "Tackle", type: "Bug", rarity: "Common"},
    {name: "Venomoth", hp: 70, atk: 65, move: "Confusion", type: "Bug", rarity: "Uncommon"},
    {name: "Diglett", hp: 10, atk: 55, move: "Scratch", type: "Ground", rarity: "Common"},
    {name: "Dugtrio", hp: 35, atk: 80, move: "Dig", type: "Ground", rarity: "Uncommon"},
    {name: "Meowth", hp: 40, atk: 45, move: "Scratch", type: "Normal", rarity: "Common"},
    {name: "Persian", hp: 65, atk: 70, move: "Slash", type: "Normal", rarity: "Uncommon"},
    {name: "Psyduck", hp: 50, atk: 52, move: "Scratch", type: "Water", rarity: "Common"},
    {name: "Golduck", hp: 80, atk: 82, move: "Water Gun", type: "Water", rarity: "Uncommon"},
    {name: "Mankey", hp: 40, atk: 80, move: "Karate Chop", type: "Fighting", rarity: "Common"},
    {name: "Primeape", hp: 65, atk: 105, move: "Low Kick", type: "Fighting", rarity: "Uncommon"},
    {name: "Growlithe", hp: 55, atk: 70, move: "Ember", type: "Fire", rarity: "Common"},
    {name: "Arcanine", hp: 90, atk: 110, move: "Flamethrower", type: "Fire", rarity: "Uncommon"},
    {name: "Poliwag", hp: 40, atk: 50, move: "Bubble", type: "Water", rarity: "Common"},
    {name: "Poliwhirl", hp: 65, atk: 65, move: "Water Gun", type: "Water", rarity: "Uncommon"},
    {name: "Poliwrath", hp: 90, atk: 85, move: "Hydro Pump", type: "Water", rarity: "Rare"},
    {name: "Abra", hp: 25, atk: 20, move: "Teleport", type: "Psychic", rarity: "Common"},
    {name: "Kadabra", hp: 40, atk: 35, move: "Confusion", type: "Psychic", rarity: "Uncommon"},
    {name: "Alakazam", hp: 55, atk: 50, move: "Psybeam", type: "Psychic", rarity: "Rare"},
    {name: "Machop", hp: 70, atk: 80, move: "Karate Chop", type: "Fighting", rarity: "Common"},
    {name: "Machoke", hp: 80, atk: 100, move: "Low Kick", type: "Fighting", rarity: "Uncommon"},
    {name: "Machamp", hp: 90, atk: 130, move: "Submission", type: "Fighting", rarity: "Rare"},
    {name: "Bellsprout", hp: 50, atk: 75, move: "Vine Whip", type: "Grass", rarity: "Common"},
    {name: "Weepinbell", hp: 65, atk: 90, move: "Razor Leaf", type: "Grass", rarity: "Uncommon"},
    {name: "Victreebel", hp: 80, atk: 105, move: "Solar Beam", type: "Grass", rarity: "Rare"},
    {name: "Tentacool", hp: 40, atk: 40, move: "Poison Sting", type: "Water", rarity: "Common"},
    {name: "Tentacruel", hp: 80, atk: 70, move: "Bubble Beam", type: "Water", rarity: "Uncommon"},
    {name: "Geodude", hp: 40, atk: 80, move: "Tackle", type: "Rock", rarity: "Common"},
    {name: "Graveler", hp: 55, atk: 95, move: "Rock Throw", type: "Rock", rarity: "Uncommon"},
    {name: "Golem", hp: 80, atk: 120, move: "Rock Slide", type: "Rock", rarity: "Rare"},
    {name: "Ponyta", hp: 50, atk: 85, move: "Ember", type: "Fire", rarity: "Common"},
    {name: "Rapidash", hp: 65, atk: 100, move: "Stomp", type: "Fire", rarity: "Uncommon"},
    {name: "Slowpoke", hp: 90, atk: 65, move: "Water Gun", type: "Water", rarity: "Common"},
    {name: "Slowbro", hp: 95, atk: 75, move: "Confusion", type: "Water", rarity: "Uncommon"},
    {name: "Magnemite", hp: 25, atk: 35, move: "Tackle", type: "Electric", rarity: "Common"},
    {name: "Magneton", hp: 50, atk: 60, move: "Thunder Shock", type: "Electric", rarity: "Uncommon"},
    {name: "Farfetch'd", hp: 52, atk: 65, move: "Peck", type: "Normal", rarity: "Uncommon"},
    {name: "Doduo", hp: 35, atk: 85, move: "Peck", type: "Normal", rarity: "Common"},
    {name: "Dodrio", hp: 60, atk: 110, move: "Drill Peck", type: "Normal", rarity: "Uncommon"},
    {name: "Seel", hp: 65, atk: 45, move: "Headbutt", type: "Water", rarity: "Common"},
    {name: "Dewgong", hp: 90, atk: 70, move: "Aurora Beam", type: "Water", rarity: "Uncommon"},
    {name: "Grimer", hp: 80, atk: 80, move: "Pound", type: "Poison", rarity: "Common"},
    {name: "Muk", hp: 105, atk: 105, move: "Sludge", type: "Poison", rarity: "Uncommon"},
    {name: "Shellder", hp: 30, atk: 65, move: "Tackle", type: "Water", rarity: "Common"},
    {name: "Cloyster", hp: 50, atk: 95, move: "Aurora Beam", type: "Water", rarity: "Uncommon"},
    {name: "Gastly", hp: 30, atk: 35, move: "Lick", type: "Ghost", rarity: "Common"},
    {name: "Haunter", hp: 45, atk: 50, move: "Night Shade", type: "Ghost", rarity: "Uncommon"},
    {name: "Gengar", hp: 60, atk: 65, move: "Dream Eater", type: "Ghost", rarity: "Rare"},
    {name: "Onix", hp: 35, atk: 45, move: "Tackle", type: "Rock", rarity: "Common"},
    {name: "Drowzee", hp: 60, atk: 48, move: "Confusion", type: "Psychic", rarity: "Common"},
    {name: "Hypno", hp: 85, atk: 73, move: "Psybeam", type: "Psychic", rarity: "Uncommon"},
    {name: "Krabby", hp: 30, atk: 105, move: "Vice Grip", type: "Water", rarity: "Common"},
    {name: "Kingler", hp: 55, atk: 130, move: "Crabhammer", type: "Water", rarity: "Uncommon"},
    {name: "Voltorb", hp: 40, atk: 30, move: "Tackle", type: "Electric", rarity: "Common"},
    {name: "Electrode", hp: 60, atk: 50, move: "Sonic Boom", type: "Electric", rarity: "Uncommon"},
    {name: "Exeggcute", hp: 60, atk: 40, move: "Barrage", type: "Grass", rarity: "Common"},
    {name: "Exeggutor", hp: 95, atk: 95, move: "Egg Bomb", type: "Grass", rarity: "Uncommon"},
    {name: "Cubone", hp: 50, atk: 50, move: "Bone Club", type: "Ground", rarity: "Common"},
    {name: "Marowak", hp: 60, atk: 80, move: "Thrash", type: "Ground", rarity: "Uncommon"},
    {name: "Hitmonlee", hp: 50, atk: 120, move: "Jump Kick", type: "Fighting", rarity: "Rare"},
    {name: "Hitmonchan", hp: 50, atk: 105, move: "Mega Punch", type: "Fighting", rarity: "Rare"},
    {name: "Lickitung", hp: 90, atk: 55, move: "Lick", type: "Normal", rarity: "Uncommon"},
    {name: "Koffing", hp: 40, atk: 65, move: "Smog", type: "Poison", rarity: "Common"},
    {name: "Weezing", hp: 65, atk: 90, move: "Sludge", type: "Poison", rarity: "Uncommon"},
    {name: "Rhyhorn", hp: 80, atk: 85, move: "Stomp", type: "Ground", rarity: "Uncommon"},
    {name: "Rhydon", hp: 105, atk: 130, move: "Horn Drill", type: "Ground", rarity: "Rare"},
    {name: "Chansey", hp: 250, atk: 5, move: "Double Slap", type: "Normal", rarity: "Rare"},
    {name: "Tangela", hp: 65, atk: 55, move: "Constrict", type: "Grass", rarity: "Uncommon"},
    {name: "Kangaskhan", hp: 105, atk: 95, move: "Mega Punch", type: "Normal", rarity: "Rare"},
    {name: "Horsea", hp: 30, atk: 40, move: "Bubble", type: "Water", rarity: "Common"},
    {name: "Seadra", hp: 55, atk: 65, move: "Water Gun", type: "Water", rarity: "Uncommon"},
    {name: "Goldeen", hp: 45, atk: 67, move: "Peck", type: "Water", rarity: "Common"},
    {name: "Seaking", hp: 80, atk: 92, move: "Horn Attack", type: "Water", rarity: "Uncommon"},
    {name: "Staryu", hp: 30, atk: 45, move: "Water Gun", type: "Water", rarity: "Common"},
    {name: "Starmie", hp: 60, atk: 75, move: "Swift", type: "Water", rarity: "Uncommon"},
    {name: "Mr. Mime", hp: 40, atk: 45, move: "Confusion", type: "Psychic", rarity: "Uncommon"},
    {name: "Scyther", hp: 70, atk: 110, move: "Wing Attack", type: "Bug", rarity: "Rare"},
    {name: "Jynx", hp: 65, atk: 50, move: "Powder Snow", type: "Psychic", rarity: "Uncommon"},
    {name: "Electabuzz", hp: 65, atk: 83, move: "Thunder Punch", type: "Electric", rarity: "Rare"},
    {name: "Magmar", hp: 65, atk: 95, move: "Ember", type: "Fire", rarity: "Rare"},
    {name: "Pinsir", hp: 65, atk: 125, move: "Vice Grip", type: "Bug", rarity: "Rare"},
    {name: "Tauros", hp: 75, atk: 100, move: "Tackle", type: "Normal", rarity: "Rare"},
    {name: "Magikarp", hp: 20, atk: 10, move: "Splash", type: "Water", rarity: "Common"},
    {name: "Gyarados", hp: 95, atk: 125, move: "Dragon Rage", type: "Water", rarity: "Rare"},
    {name: "Lapras", hp: 130, atk: 85, move: "Water Gun", type: "Water", rarity: "Rare"},
    {name: "Ditto", hp: 48, atk: 48, move: "Transform", type: "Normal", rarity: "Rare"},
    {name: "Eevee", hp: 55, atk: 55, move: "Tackle", type: "Normal", rarity: "Uncommon"},
    {name: "Vaporeon", hp: 130, atk: 65, move: "Water Gun", type: "Water", rarity: "Rare"},
    {name: "Jolteon", hp: 65, atk: 65, move: "Thunder Shock", type: "Electric", rarity: "Rare"},
    {name: "Flareon", hp: 65, atk: 130, move: "Ember", type: "Fire", rarity: "Rare"},
    {name: "Porygon", hp: 65, atk: 60, move: "Tackle", type: "Normal", rarity: "Rare"},
    {name: "Omanyte", hp: 35, atk: 40, move: "Water Gun", type: "Rock", rarity: "Uncommon"},
    {name: "Omastar", hp: 70, atk: 60, move: "Hydro Pump", type: "Rock", rarity: "Rare"},
    {name: "Kabuto", hp: 30, atk: 80, move: "Scratch", type: "Rock", rarity: "Uncommon"},
    {name: "Kabutops", hp: 60, atk: 115, move: "Slash", type: "Rock", rarity: "Rare"},
    {name: "Aerodactyl", hp: 80, atk: 105, move: "Wing Attack", type: "Rock", rarity: "Rare"},
    {name: "Snorlax", hp: 160, atk: 110, move: "Body Slam", type: "Normal", rarity: "Rare"},
    {name: "Articuno", hp: 90, atk: 85, move: "Ice Beam", type: "Ice", rarity: "Legendary"},
    {name: "Zapdos", hp: 90, atk: 90, move: "Thunder Shock", type: "Electric", rarity: "Legendary"},
    {name: "Moltres", hp: 90, atk: 100, move: "Ember", type: "Fire", rarity: "Legendary"},
    {name: "Dratini", hp: 41, atk: 64, move: "Wrap", type: "Dragon", rarity: "Uncommon"},
    {name: "Dragonair", hp: 61, atk: 84, move: "Dragon Rage", type: "Dragon", rarity: "Rare"},
    {name: "Dragonite", hp: 91, atk: 134, move: "Hyper Beam", type: "Dragon", rarity: "Legendary"},
    {name: "Mewtwo", hp: 106, atk: 110, move: "Psychic", type: "Psychic", rarity: "Mythical"},
    {name: "Mew", hp: 100, atk: 100, move: "Pound", type: "Psychic", rarity: "Mythical"}
];


module.exports = pokedex